name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace credentials in HTML
        run: |
          # Create a temporary file with the Firebase config
          echo '${{ secrets.FIREBASE_CONFIG }}' > firebase-config.json
          
          # Replace Discord Client ID
          sed -i "s/DISCORD_CLIENT_ID_PLACEHOLDER/'${{ secrets.DISCORD_CLIENT_ID }}'/g" index.html
          
          # Replace Firebase config using node
          node -e "
            const fs = require('fs');
            const html = fs.readFileSync('index.html', 'utf8');
            const config = fs.readFileSync('firebase-config.json', 'utf8');
            const newHtml = html.replace('FIREBASE_CONFIG_PLACEHOLDER', config);
            fs.writeFileSync('index.html', newHtml);
          "
          
          # Clean up
          rm firebase-config.json

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true