name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > firebase-credentials.json
          
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        
      - name: Initialize Firebase in project
        run: |
          FIREBASE_CONFIG=$(cat firebase-credentials.json)
          # Inject Firebase config into index.html
          sed -i "s|projectId: \"quaipepe-70873\",|projectId: \"quaipepe-70873\",\n            apiKey: \"$FIREBASE_API_KEY\",\n            authDomain: \"quaipepe-70873.firebaseapp.com\",\n            storageBucket: \"quaipepe-70873.appspot.com\",|" index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .