# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace credentials
        run: |
          # Create a temporary Node.js script to handle the replacements
          cat > replace.js <<'EOL'
          const fs = require('fs');
          let html = fs.readFileSync('index.html', 'utf8');
          
          // Replace Discord client ID without quotes
          html = html.replace(
            /DISCORD_CLIENT_ID_PLACEHOLDER/g,
            process.env.DISCORD_CLIENT_ID
          );
          
          // Replace Firebase config
          html = html.replace(
            '// Rest will be injected by GitHub Actions',
            process.env.FIREBASE_CONFIG
          );
          
          fs.writeFileSync('index.html', html);
          EOL
          
          # Run the replacement script
          node replace.js
        env:
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true