# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace Discord Client ID
        run: |
          # Replace without adding quotes
          sed -i "s/DISCORD_CLIENT_ID_PLACEHOLDER/${{ secrets.DISCORD_CLIENT_ID }}/g" index.html

      - name: Replace Firebase Config
        run: |
          echo '${{ secrets.FIREBASE_CONFIG }}' > config.txt
          CONFIG=$(cat config.txt | tr -d '\n' | sed 's/\"/\\"/g')
          sed -i "s|// Rest will be injected by GitHub Actions|$CONFIG|g" index.html
          rm config.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true