# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace credentials
        run: |
          # Create a temporary Node.js script to handle the replacements
          cat > replace.js <<'EOL'
          const fs = require('fs');
          let html = fs.readFileSync('index.html', 'utf8');
          
          // Create a safe version of Firebase config
          const config = {
            apiKey: process.env.FIREBASE_API_KEY,
            projectId: "quaipepe-70873",
            authDomain: "quaipepe-70873.firebaseapp.com",
            storageBucket: "quaipepe-70873.appspot.com"
          };
          
          // Replace Firebase config
          html = html.replace('// Rest will be injected by GitHub Actions', JSON.stringify(config));
          
          // Replace Discord client ID
          html = html.replace('DISCORD_CLIENT_ID_PLACEHOLDER', `"${process.env.DISCORD_CLIENT_ID}"`);
          
          fs.writeFileSync('index.html', html);
          EOL
          
          # Run the replacement script
          node replace.js
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true